# Site settings
title: FintechObserver Fintech观察家
SEOTitle: Fintech观察家的博客 | FintechObserver Fintech观察家
header-img: img/post-bg-desk.jpg
email: anthonyzha@gmail.com
description: "Every failure is leading towards success."
keyword: "Fintech,Fintech观察家,FintechObserver,P2P loan,blockChain,BTC,Crowd funding , 阿奎, 增奎, 赵增奎, 新金融，金融科技"
url: "http://runrun88.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/runrun88/runrun88.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Fintech entrepreneur and Fintech investor led you know more about Fintech "
sidebar-avatar: /img/zhao.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     Fintech观察家
zhihu_username:     zhaoakui
github_username:     runrun88
facebook_username:  anthony.zhao
weixin_username:   122256394
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: e299704f249dd53d6648                            #生成的clientID
  clientSecret: ea691b7f3053a54a57be45a013ef3fda7fb4449f    #生成的clientSecret
  repo: runrun88.github.io    #仓库名称
  owner: runrun88    #github用户名
  admin: FintechObserver
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: fintechobserver.com              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Fintech innovation lab",
        href: "http://www.fintechinnovationlab.com/"
    },{
        title: "微信公众号·Fintech观察家",
        href: "http://mp.weixin.qq.com/profile?src=3&timestamp=1549958588&ver=1&signature=vQhwrB1yb6hM-bXoJ2NDoPMMmnmrqGBfkscLlUbw*RJPTcWL-O6Y5JmFzRVIsWJdK*SJ-J*1L*MPZ7cbm5dTPw=="
    },{
        title: "网贷之家",
        href: "https://www.wdzj.com/"
    },{
        title: "CoinMarketCap",
        href: "https://coinmarketcap.com/"
    }
]
